jobs/gpref: unset GCC_ROOT which breaks /usr/bin/gcc
	$ echo -e '#include <stdio.h>\nint main() { return 0; }' > test.c
	$ /usr/bin/gcc -o test test.c
	In file included from test.c:1:0:
	/usr/include/stdio.h:33:21: fatal error: stddef.h: No such file or
	directory

	    include <stddef.h>
				 ^
	    compilation terminated.

https://uschpc.atlassian.net/servicedesk/customer/portal/7/ARC-244